@echo off
echo Starting Fund Assistant...
echo Please ensure you have Python installed.
echo Installing dependencies...
pip install -r requirements.txt
echo Starting Streamlit App...
streamlit run app.py
pause
